version: "3"
services:
  app:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMEN: "Development"
