apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: microservice-dotnet-sdk5
  name: microservice-dotnet-sdk5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: microservice-dotnet-sdk5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservice-dotnet-sdk5
    spec:
      containers:
      - image: samuelngarciar/microservice-dotnet-sdk5
        imagePullPolicy: Always
        name: microservice-dotnet-sdk5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-dotnet-sdk5
spec:
  selector:
    app: microservice-dotnet-sdk5
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
