name: .NET CI/CD Pipeline
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Build Docker container
      - name: Setup Docker
        run: |
          cd ./hello-world-dotnet
          docker build . -t hello-world-dotnet:latest
          docker run -d --rm \
            -e ASPNETCORE_URLS=http://+:5000 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -p 5000:5000 \
            hello-world-dotnet:latest
      
      # Verify Application Accessibility
      - name: Verify Application
        run: |
          sleep 5
          curl http://localhost:5000
      
      # Security Checks
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:5000'
          cmd_options: '-a'
          fail_action: false
          

      # Dependency Scanning     
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: 'test'

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
