name: .NET CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Use Pre-configured Docker Image
      - name: Setup Docker
        run: |
          docker pull mcr.microsoft.com/dotnet/sdk:5.0
          docker run -d -p 5000:5000 --name myapp -v $(pwd):/app -w /app mcr.microsoft.com/dotnet/sdk:5.0 /bin/bash -c "dotnet restore && dotnet build --no-restore && dotnet publish -c Release -o out && dotnet run"
      
      # Security Checks
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:5000'
      
      - name: Dependency Scanning
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
