name: .NET CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      webapp:
        image: mcr.microsoft.com/dotnet/aspnet:5.0
        ports:
          - 5000:5000
        options: >-
          --name webapp
          --health-cmd "curl --fail http://localhost:5000 || exit 1"
          --health-interval 50s
          --health-timeout 30s
          --health-retries 8
    steps:
      - uses: actions/checkout@v3
      
      # Build & Test
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.x'
      
      - name: Restore NuGet Packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      - name: Publish
        run: dotnet publish -c Release -o out
      
      - name: Run Web App
        run: |
          docker build -t myapp .
          docker run -d -p 5000:5000 --name myapp myapp
      
      # Security Checks
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:5000'
      
      - name: Dependency Scanning
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
