name: .NET CI/CD Pipeline
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  issues: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Build Docker container
      - name: Setup Docker
        run: |
          cd ./hello-world-dotnet
          docker build . -t hello-world-dotnet:latest
          docker run -d --rm \
            -e ASPNETCORE_URLS=http://+:5000 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -p 5000:5000 \
            hello-world-dotnet:latest
      
      # Verify Application Accessibility
      - name: Verify Application
        run: |
          sleep 5
          curl http://localhost:5000
      
      # Security Checks
      #- name: OWASP ZAP Scan
        #uses: zaproxy/action-full-scan@v0.12.0
        #with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          #docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          #target: 'http://localhost:5000'
          #cmd_options: '-a'
          ##fail_action: false

      # deployment
      - name: Setup Docker
        run: |
          curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl version --client


