name: .NET CI/CD Pipelin
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Security Checks
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost:5000'
      
      - name: Dependency Scanning
        uses: snyk/snyk-github-action@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Build & Test
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.x'
      
      - name: Restore NuGet Packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
      # Docker & Deploy
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Image
        run: |
          docker build -t $DOCKER_USERNAME/myapp .
          docker push $DOCKER_USERNAME/myapp:latest
      
      - name: Deploy to Kubernetes
        uses: kubernetes/deploy-action@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
